global:
  scrape_interval: 3s
  scrape_timeout: 2s  

scrape_configs:
  - job_name: 'debezium'
    static_configs:
      - targets: ['<observed_machine>:7070']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['<observed_machine>:7071']
  - job_name: 'mysql'
    static_configs:
      - targets: ['<observed_machine>:7075']
